//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyID { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductID { get; set; }
        public int StockID { get; set; }
        public int Count { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
